import 'package:immo_scanner/core/app_export.dart';import 'package:immo_scanner/presentation/add_new_property_select_amenities_screen/models/add_new_property_select_amenities_model.dart';class AddNewPropertySelectAmenitiesController extends GetxController {Rx<AddNewPropertySelectAmenitiesModel> addNewPropertySelectAmenitiesModelObj = AddNewPropertySelectAmenitiesModel().obs;

 }
