// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJhbA1XlhGbz55j-9xNAa3qubKIqNC_qo',
    appId: '1:42207824215:web:032c6f86d8ff34f55ed612',
    messagingSenderId: '42207824215',
    projectId: 'immo-scanner',
    authDomain: 'immo-scanner.firebaseapp.com',
    storageBucket: 'immo-scanner.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuZJQbkIPnZGU1LkGYH4J3NpKWk7WwzAI',
    appId: '1:42207824215:android:47df0fecc19095185ed612',
    messagingSenderId: '42207824215',
    projectId: 'immo-scanner',
    storageBucket: 'immo-scanner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApITxBMWAbmmbWuHUSmLEtmwa3oGbQDyg',
    appId: '1:42207824215:ios:daab1ddce84ae29c5ed612',
    messagingSenderId: '42207824215',
    projectId: 'immo-scanner',
    storageBucket: 'immo-scanner.appspot.com',
    androidClientId: '42207824215-5nd7dgmo4njpeond03g0er6583227gbc.apps.googleusercontent.com',
    iosClientId: '42207824215-9kfjfm22ikjs8uv5btq655i2bfcapo0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );
}
